/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { BaseResponse_BasicInformation_ } from './models/BaseResponse_BasicInformation_';
export type { BaseResponse_boolean_ } from './models/BaseResponse_boolean_';
export type { BaseResponse_ClockInInfoVo_ } from './models/BaseResponse_ClockInInfoVo_';
export type { BaseResponse_ClockReport_ } from './models/BaseResponse_ClockReport_';
export type { BaseResponse_CoinDetail_ } from './models/BaseResponse_CoinDetail_';
export type { BaseResponse_DailyCheckIn_ } from './models/BaseResponse_DailyCheckIn_';
export type { BaseResponse_InitClockInfo_ } from './models/BaseResponse_InitClockInfo_';
export type { BaseResponse_List_BasicInformation_ } from './models/BaseResponse_List_BasicInformation_';
export type { BaseResponse_List_ClockInInfo_ } from './models/BaseResponse_List_ClockInInfo_';
export type { BaseResponse_List_ClockReport_ } from './models/BaseResponse_List_ClockReport_';
export type { BaseResponse_List_PlatformInfo_ } from './models/BaseResponse_List_PlatformInfo_';
export type { BaseResponse_List_ProductInfo_ } from './models/BaseResponse_List_ProductInfo_';
export type { BaseResponse_List_UserVO_ } from './models/BaseResponse_List_UserVO_';
export type { BaseResponse_long_ } from './models/BaseResponse_long_';
export type { BaseResponse_Page_BasicInformation_ } from './models/BaseResponse_Page_BasicInformation_';
export type { BaseResponse_Page_ClockInInfo_ } from './models/BaseResponse_Page_ClockInInfo_';
export type { BaseResponse_Page_ClockReport_ } from './models/BaseResponse_Page_ClockReport_';
export type { BaseResponse_Page_CoinDetail_ } from './models/BaseResponse_Page_CoinDetail_';
export type { BaseResponse_Page_DailyCheckIn_ } from './models/BaseResponse_Page_DailyCheckIn_';
export type { BaseResponse_Page_PlatformInfo_ } from './models/BaseResponse_Page_PlatformInfo_';
export type { BaseResponse_Page_ProductInfo_ } from './models/BaseResponse_Page_ProductInfo_';
export type { BaseResponse_Page_UserVO_ } from './models/BaseResponse_Page_UserVO_';
export type { BaseResponse_PlatformInfo_ } from './models/BaseResponse_PlatformInfo_';
export type { BaseResponse_ProductInfo_ } from './models/BaseResponse_ProductInfo_';
export type { BaseResponse_User_ } from './models/BaseResponse_User_';
export type { BaseResponse_UserVO_ } from './models/BaseResponse_UserVO_';
export type { BasicInformation } from './models/BasicInformation';
export type { BasicInformationAddRequest } from './models/BasicInformationAddRequest';
export type { BasicInformationQueryRequest } from './models/BasicInformationQueryRequest';
export type { BasicInformationUpdateRequest } from './models/BasicInformationUpdateRequest';
export type { ClockInInfo } from './models/ClockInInfo';
export type { ClockInInfoAddRequest } from './models/ClockInInfoAddRequest';
export type { ClockInInfoQueryRequest } from './models/ClockInInfoQueryRequest';
export type { ClockInInfoUpdateRequest } from './models/ClockInInfoUpdateRequest';
export type { ClockInInfoVo } from './models/ClockInInfoVo';
export type { ClockReport } from './models/ClockReport';
export type { ClockReportAddRequest } from './models/ClockReportAddRequest';
export type { ClockReportQueryRequest } from './models/ClockReportQueryRequest';
export type { ClockReportUpdateRequest } from './models/ClockReportUpdateRequest';
export type { CoinDetail } from './models/CoinDetail';
export type { CoinDetailQueryRequest } from './models/CoinDetailQueryRequest';
export type { DailyCheckIn } from './models/DailyCheckIn';
export type { DailyCheckInQueryRequest } from './models/DailyCheckInQueryRequest';
export type { DayReport } from './models/DayReport';
export type { DeleteRequest } from './models/DeleteRequest';
export type { IdRequest } from './models/IdRequest';
export type { InitClockInfo } from './models/InitClockInfo';
export { ModelAndView } from './models/ModelAndView';
export type { MonthReport } from './models/MonthReport';
export type { OrderItem } from './models/OrderItem';
export type { Page_BasicInformation_ } from './models/Page_BasicInformation_';
export type { Page_ClockInInfo_ } from './models/Page_ClockInInfo_';
export type { Page_ClockReport_ } from './models/Page_ClockReport_';
export type { Page_CoinDetail_ } from './models/Page_CoinDetail_';
export type { Page_DailyCheckIn_ } from './models/Page_DailyCheckIn_';
export type { Page_PlatformInfo_ } from './models/Page_PlatformInfo_';
export type { Page_ProductInfo_ } from './models/Page_ProductInfo_';
export type { Page_UserVO_ } from './models/Page_UserVO_';
export type { PlatformInfo } from './models/PlatformInfo';
export type { PlatformInfoAddRequest } from './models/PlatformInfoAddRequest';
export type { PlatformInfoQueryRequest } from './models/PlatformInfoQueryRequest';
export type { PlatformInfoUpdateRequest } from './models/PlatformInfoUpdateRequest';
export type { ProductInfo } from './models/ProductInfo';
export type { ProductInfoAddRequest } from './models/ProductInfoAddRequest';
export type { ProductInfoQueryRequest } from './models/ProductInfoQueryRequest';
export type { ProductInfoUpdateRequest } from './models/ProductInfoUpdateRequest';
export type { Report } from './models/Report';
export type { User } from './models/User';
export type { UserAddRequest } from './models/UserAddRequest';
export type { UserBindEmailRequest } from './models/UserBindEmailRequest';
export type { UserLoginRequest } from './models/UserLoginRequest';
export type { UserRegisterRequest } from './models/UserRegisterRequest';
export type { UserUnBindEmailRequest } from './models/UserUnBindEmailRequest';
export type { UserUpdateRequest } from './models/UserUpdateRequest';
export type { UserVO } from './models/UserVO';
export type { View } from './models/View';
export type { WeekReport } from './models/WeekReport';

export { BasicErrorControllerService } from './services/BasicErrorControllerService';
export { BasicInformationControllerService } from './services/BasicInformationControllerService';
export { ClockInControllerService } from './services/ClockInControllerService';
export { ClockInInfoControllerService } from './services/ClockInInfoControllerService';
export { ClockReportControllerService } from './services/ClockReportControllerService';
export { CoinDetailControllerService } from './services/CoinDetailControllerService';
export { DailyCheckInControllerService } from './services/DailyCheckInControllerService';
export { PlatformInfoControllerService } from './services/PlatformInfoControllerService';
export { ProductInfoControllerService } from './services/ProductInfoControllerService';
export { UserControllerService } from './services/UserControllerService';
